# Generated by Django 2.2.8 on 2020-01-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importado', models.BooleanField(default=False)),
                ('ncm', models.CharField(max_length=8, verbose_name='NMC')),
                ('produto', models.CharField(max_length=100, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Estoque_atual')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque mínimo')),
            ],
            options={
                'ordering': ('produto',),
            },
        ),
    ]
